version: '3.8'
services:
  template-bff:
    container_name: template-bff-api
    build:
      context: ../../
      dockerfile: ./src/Services/Bff/Teamplate.Bff.Api/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_HTTPS_PORT: 8080
      ASPNETCORE_ENVIRONMENT: "Development"
      GetterApiClientSettings__BaseUrl: "http://template-getter:8080/api/template/getter/v1/"
      SetterApiClientSettings__BaseUrl: "http://template-setter:8080/api/template/setter/v1/"
      ExporterApiClientSettings__BaseUrl: "http://template-exporter:8080/api/template/exporter/v1/"

  template-getter:
    container_name: template-getter-api
    build:
      context: ../../
      dockerfile: ./src/Services/Getter/Template.Getter.Api/Dockerfile
    ports:
      - "8086:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_HTTPS_PORT: 8080
      ASPNETCORE_ENVIRONMENT: "Development"

  template-setter:
    container_name: template-setter-api
    build:
      context: ../../
      dockerfile: ./src/Services/Setter/Template.Setter.Api/Dockerfile
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_HTTPS_PORT: 8080
      ASPNETCORE_ENVIRONMENT: "Development"
