// <auto-generated />
using System;
using Gpn.Template.Infrastructure.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gpn.Template.DatabaseUpgrade.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20250204085838_AddWorkEntity")]
    partial class AddWorkEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gpn.Template.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Gpn.Template.Domain.Entities.PersonWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("WorkId");

                    b.ToTable("PersonWork");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Gpn.Template.Domain.Entities.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Work");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Shared.Application.Core.Dal.DbSeeder.Entities.Seed", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Name");

                    b.ToTable("seed", (string)null);
                });

            modelBuilder.Entity("Gpn.Template.Domain.Entities.PersonWork", b =>
                {
                    b.HasOne("Gpn.Template.Domain.Entities.Person", "Person")
                        .WithMany("PersonWorks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gpn.Template.Domain.Entities.Work", "Work")
                        .WithMany("PersonWorks")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Gpn.Template.Domain.Entities.Person", b =>
                {
                    b.Navigation("PersonWorks");
                });

            modelBuilder.Entity("Gpn.Template.Domain.Entities.Work", b =>
                {
                    b.Navigation("PersonWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
