// <auto-generated />
using System;
using Gpn.Template.Infrastructure.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gpn.Template.DatabaseUpgrade.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20251003075501_AddOutboxEvents")]
    partial class AddOutboxEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gpn.Template.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Shared.Application.Core.Dal.DbSeeder.Entities.Seed", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Name");

                    b.ToTable("seed", (string)null);
                });

            modelBuilder.Entity("Shared.Domain.Core.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type")
                        .HasComment("Тип контента HTTP-запроса.");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correlation_id")
                        .HasComment("Идентификатор корреляции для связывания событий.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasComment("Время создания события.");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message")
                        .HasComment("Сообщение об ошибке при неудачной обработке.");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_data")
                        .HasComment("JSON-данные события.");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_type")
                        .HasComment("Тип события для маршрутизации.");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text")
                        .HasColumnName("headers_json")
                        .HasComment("JSON-сериализованные HTTP-заголовки.");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("http_method")
                        .HasComment("HTTP-метод (GET, POST, PUT, DELETE).");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key")
                        .HasComment("Ключ идемпотентности для предотвращения дублирования.");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lock_expires_at")
                        .HasComment("Время истечения блокировки.");

                    b.Property<string>("LockId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lock_id")
                        .HasComment("Идентификатор блокировки для конкурентной обработки.");

                    b.Property<int>("MaxRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_retry_count")
                        .HasComment("Максимальное количество попыток.");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_attempt_at")
                        .HasComment("Время следующей попытки обработки.");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority")
                        .HasComment("Приоритет события (0 - наивысший).");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_at")
                        .HasComment("Время успешной обработки события.");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count")
                        .HasComment("Количество попыток обработки.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("Текущий статус события.");

                    b.Property<string>("TenantId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tenant_id")
                        .HasComment("Идентификатор арендатора для мультитенантности.");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("timeout_seconds")
                        .HasComment("Таймаут HTTP-запроса в секундах.");

                    b.Property<string>("TraceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("trace_id")
                        .HasComment("Идентификатор трейса для распределенного трейсинга.");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url")
                        .HasComment("URL для HTTP-запроса.");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_events_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_events_created_at");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_events_idempotency_key");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_outbox_events_next_attempt_at");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_outbox_events_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_outbox_events_status");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_events_status_next_attempt");

                    b.ToTable("outbox_events", null, t =>
                        {
                            t.HasComment("Таблица событий Outbox для надежной доставки сообщений.");
                        });

                    b.UseTptMappingStrategy();
                });
#pragma warning restore 612, 618
        }
    }
}
