// <auto-generated />
using System;
using Gpn.Template.Infrastructure.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gpn.Template.DatabaseUpgrade.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gpn.Template.Domain.Entities.Person", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("email");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.ToTable("Person");

                b.UseTptMappingStrategy();
            });

            modelBuilder.Entity("Shared.Application.Core.Dal.DbSeeder.Entities.Seed", b =>
            {
                b.Property<string>("Name")
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.HasKey("Name");

                b.ToTable("seed", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
